// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gradientDomainHDRCompression
NumericMatrix gradientDomainHDRCompression(NumericMatrix extractedLuminance, double alpha, double beta, double delta, double theta, double epsilon, double saturation);
RcppExport SEXP astror_gradientDomainHDRCompression(SEXP extractedLuminanceSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP deltaSEXP, SEXP thetaSEXP, SEXP epsilonSEXP, SEXP saturationSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type extractedLuminance(extractedLuminanceSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type saturation(saturationSEXP);
    __result = Rcpp::wrap(gradientDomainHDRCompression(extractedLuminance, alpha, beta, delta, theta, epsilon, saturation));
    return __result;
END_RCPP
}
